import type {
  BrandClassicPaint,
  GuardrailConfig,
  PaintOption,
  PartAsset,
  PartAssetReference,
  PartBrand,
  PartCategory,
  PromptPreset,
  PromptTemplate,
  ProviderConfig,
  SiteConfig,
  WorkflowConfig,
  WorkflowEdgeConfig,
  WorkflowNodeConfig,
} from "./types"
import { defaultAliasesForCategory, defaultChatEnabledForCategory, defaultReferenceHighRiskForCategory, defaultConfigTypeForCategory, defaultAssetImageVisibleForCategory, defaultSubcategoryConfigForCategory } from "./part-category-aliases"
import { buildDefaultProviderOptions } from "./provider-image-params"

const categorySeedBase: PartCategory[] = [
  { id: "wheels", label: "Wheels", labelEn: "Wheels", labelZh: "轮毂", description: "Forged wheels, colors, offsets and fitment.", sortOrder: 10 },
  { id: "calipers", label: "Brake calipers", labelEn: "Brake calipers", labelZh: "刹车卡钳", description: "Caliper colors and performance brake styles.", sortOrder: 20 },
  { id: "rear-wing", label: "Rear wing", labelEn: "Rear wing", labelZh: "尾翼/鸭尾", description: "Ducktail, trunk lip, GT wing, and rear aero pieces.", sortOrder: 30 },
  { id: "front-bumper", label: "Front aero", labelEn: "Front aero", labelZh: "前唇/前包围", description: "Front lips, splitters, and bumper profiles.", sortOrder: 40 },
  { id: "side-skirts", label: "Side skirts", labelEn: "Side skirts", labelZh: "侧裙", description: "Side extensions and lower body lines.", sortOrder: 50 },
  { id: "diffuser", label: "Diffuser", labelEn: "Diffuser", labelZh: "扩散器", description: "Rear diffusers, lower splitters, and aero fins.", sortOrder: 60 },
  { id: "exhaust", label: "Exhaust", labelEn: "Exhaust", labelZh: "排气", description: "Tip finishes and rear exhaust layouts.", sortOrder: 70 },
  { id: "hood", label: "Hood", labelEn: "Hood", labelZh: "机盖", description: "OE-style, vented, and carbon hood panels.", sortOrder: 80 },
  { id: "lights", label: "Lights", labelEn: "Lights", labelZh: "车灯", description: "Smoked light film and lamp treatment.", sortOrder: 90 },
  { id: "wrap", label: "Wrap", labelEn: "Wrap", labelZh: "改色膜/车漆", description: "Body finish, matte, gloss, satin, and metallic paint.", sortOrder: 100 },
  { id: "mirrors", label: "Mirrors", labelEn: "Mirrors", labelZh: "后视镜", description: "Mirror caps and carbon trim.", sortOrder: 110 },
  { id: "grille", label: "Grille", labelEn: "Grille", labelZh: "中网", description: "Kidney grille, mesh, and front intake detail.", sortOrder: 120 },
]

export const legacyCategoriesSeed: PartCategory[] = categorySeedBase.map((category) => ({
  ...category,
  aliases: defaultAliasesForCategory(category.id),
  chatEnabled: defaultChatEnabledForCategory(category.id),
  referenceHighRisk: defaultReferenceHighRiskForCategory(category.id),
}))

const v2CategorySeedBase: PartCategory[] = [
  { id: "wheels", label: "Wheels", labelEn: "Wheels", labelZh: "\u8f6e\u6bc2", description: "Forged wheels, colors, offsets and fitment.", sortOrder: 10 },
  { id: "calipers", label: "Brake calipers", labelEn: "Brake calipers", labelZh: "\u5361\u94b3", description: "Caliper colors, rotor choices, and brake visual upgrades.", sortOrder: 20 },
  { id: "rear-wing", label: "Rear wing", labelEn: "Rear wing", labelZh: "\u5c3e\u7ffc", description: "Fixed ducktail, lip spoiler, GT wing, swan neck, and time attack wing styles.", sortOrder: 30 },
  { id: "side-skirts", label: "Side skirts", labelEn: "Side skirts", labelZh: "\u4fa7\u88d9", description: "On/off side skirt style with black, carbon, or body-color finish.", sortOrder: 40 },
  { id: "front-bumper", label: "Front splitter", labelEn: "Front splitter", labelZh: "\u524d\u94f2", description: "On/off front splitter style with black, carbon, or body-color finish.", sortOrder: 50 },
  { id: "exhaust", label: "Exhaust layout", labelEn: "Exhaust layout", labelZh: "\u6392\u6c14", description: "Fixed rear exhaust outlet layout choices.", sortOrder: 60 },
  { id: "hood", label: "Hood", labelEn: "Hood", labelZh: "\u673a\u76d6", description: "Dry carbon hood material option.", sortOrder: 70 },
  { id: "mirrors", label: "Mirrors", labelEn: "Mirrors", labelZh: "\u540e\u89c6\u955c", description: "Dry carbon mirror cap material option.", sortOrder: 80 },
  { id: "fenders", label: "Fenders", labelEn: "Fenders", labelZh: "\u53f6\u5b50\u677f", description: "Dry carbon fender material option.", sortOrder: 90 },
  { id: "trunk-lid", label: "Trunk lid", labelEn: "Trunk lid", labelZh: "\u540e\u5907\u7bb1\u76d6", description: "Dry carbon trunk-lid material option.", sortOrder: 100 },
]

export const v2PartCategoryIds = v2CategorySeedBase.map((category) => category.id)

export const v2FrontCatalogBrandIds = [
  "brand-wing-style",
  "brand-front-splitter-style",
  "brand-side-skirt-style",
  "brand-exhaust-layout",
  "brand-dry-carbon-hood",
  "brand-dry-carbon-mirrors",
  "brand-dry-carbon-fenders",
  "brand-dry-carbon-trunk",
]

export const v2FrontCatalogAssetIds = [
  "wing-ducktail",
  "wing-lip-spoiler",
  "wing-gt-wing",
  "wing-swan-neck",
  "wing-time-attack",
  "front-splitter-style",
  "side-skirts-style",
  "exhaust-single-left",
  "exhaust-single-right",
  "exhaust-dual-left",
  "exhaust-dual-right",
  "exhaust-quad",
  "exhaust-dual-single",
  "exhaust-center-single",
  "exhaust-center-dual",
  "exhaust-center-quad",
  "dry-carbon-hood",
  "dry-carbon-mirrors",
  "dry-carbon-fenders",
  "dry-carbon-trunk-lid",
]

export const categoriesSeed: PartCategory[] = v2CategorySeedBase.map((category) => ({
  ...category,
  aliases: defaultAliasesForCategory(category.id),
  chatEnabled: defaultChatEnabledForCategory(category.id),
  referenceHighRisk: defaultReferenceHighRiskForCategory(category.id),
  configType: defaultConfigTypeForCategory(category.id),
  assetImageVisible: defaultAssetImageVisibleForCategory(category.id),
  subcategoryConfig: defaultSubcategoryConfigForCategory(category.id),
}))

export const brandsSeed: PartBrand[] = [
  { id: "brand-bbs", categoryId: "wheels", label: "BBS", sortOrder: 10, active: true },
  { id: "brand-brembo", categoryId: "calipers", label: "Brembo", sortOrder: 10, active: true },
  { id: "brand-ap-racing", categoryId: "calipers", label: "AP Racing", sortOrder: 20, active: true },
  { id: "brand-m-performance", categoryId: "rear-wing", label: "M Performance", sortOrder: 10, active: true },
  { id: "brand-kies", categoryId: "rear-wing", label: "Kies Motorsports", sortOrder: 20, active: true },
  { id: "brand-varis", categoryId: "front-bumper", label: "Varis", sortOrder: 10, active: true },
  { id: "brand-rsc", categoryId: "side-skirts", label: "RSC", sortOrder: 10, active: true },
  { id: "brand-rsc-diffuser", categoryId: "diffuser", label: "RSC", sortOrder: 10, active: true },
  { id: "brand-akrapovic", categoryId: "exhaust", label: "Akrapovic", sortOrder: 10, active: true },
  { id: "brand-seibon", categoryId: "hood", label: "Seibon", sortOrder: 10, active: true },
  { id: "brand-vland", categoryId: "lights", label: "VLAND", sortOrder: 10, active: true },
  { id: "brand-bmw-m-performance", categoryId: "grille", label: "BMW M Performance", sortOrder: 10, active: true },
  { id: "brand-oem-plus", categoryId: "mirrors", label: "OEM+", sortOrder: 10, active: true },
  { id: "brand-wing-style", categoryId: "rear-wing", label: "Style Library", sortOrder: 30, active: true },
  { id: "brand-front-splitter-style", categoryId: "front-bumper", label: "Style Library", sortOrder: 20, active: true },
  { id: "brand-side-skirt-style", categoryId: "side-skirts", label: "Style Library", sortOrder: 20, active: true },
  { id: "brand-exhaust-layout", categoryId: "exhaust", label: "Layout Library", sortOrder: 20, active: true },
  { id: "brand-dry-carbon-hood", categoryId: "hood", label: "Dry Carbon", sortOrder: 20, active: true },
  { id: "brand-dry-carbon-mirrors", categoryId: "mirrors", label: "Dry Carbon", sortOrder: 20, active: true },
  { id: "brand-dry-carbon-fenders", categoryId: "fenders", label: "Dry Carbon", sortOrder: 10, active: true },
  { id: "brand-dry-carbon-trunk", categoryId: "trunk-lid", label: "Dry Carbon", sortOrder: 10, active: true },
  { id: "brand-3m", categoryId: "wrap", label: "3M", sortOrder: 10, active: true },
]

export const paintsSeed: PaintOption[] = [
  { id: "factory", label: "Factory paint", hex: "#6f7682", prompt: "保持原车车身漆面颜色、光泽、反射、阴影和各钣金面连续性，不要改色。" },
  { id: "pure-black", label: "Pure black", hex: "#050506", prompt: "将车辆车身漆面改为深亮黑色，保留原图真实反射、清漆高光、车身折线和阴影。" },
  { id: "matte-black", label: "Matte black", hex: "#111214", prompt: "将车辆车身漆面改为哑光黑色，保持曲面、钣金缝隙、光照方向和真实材质层次。" },
  { id: "pearl-white", label: "Pearl white", hex: "#f2f1ea", prompt: "将车辆车身漆面改为珍珠白，保留细腻金属/珠光层次和原图环境反射。" },
  { id: "nardo-gray", label: "Nardo gray", hex: "#8a8d8f", prompt: "将车辆车身漆面改为纳多灰，保留原图高光、阴影、反射、车身折线和环境色温。" },
  { id: "racing-blue", label: "Racing blue", hex: "#0d57d6", prompt: "将车辆车身漆面改为高饱和赛车蓝，保持真实亮面反射和阴影关系。" },
  { id: "track-red", label: "Track red", hex: "#cf1f2f", prompt: "将车辆车身漆面改为鲜明赛道红，保留真实清漆反射和原图光照方向。" },
]

export const classicPaintsSeed: BrandClassicPaint[] = [
  {
    id: "default-bmw-abu-dhabi-blue",
    brand: "Default",
    label: "BMW Abu Dhabi Blue",
    labelZh: "宝马阿布扎比蓝",
    labelEn: "BMW Abu Dhabi Blue",
    colorCode: "",
    hex: "#1F6F8B",
    material: "metallic",
    prompt: "将车身漆面改为宝马阿布扎比蓝 / BMW Abu Dhabi Blue，保留运动感蓝色金属漆层次、真实清漆高光、车身折线、环境反射和原图光照方向。",
    active: true,
    isDefault: true,
    sortOrder: 10,
  },
  {
    id: "default-ferrari-rosso-corsa",
    brand: "Default",
    label: "Ferrari Rosso Corsa",
    labelZh: "法拉利赛道红",
    labelEn: "Ferrari Rosso Corsa",
    colorCode: "",
    hex: "#D40000",
    material: "gloss",
    prompt: "将车身漆面改为法拉利赛道红 / Ferrari Rosso Corsa，保留经典跑车红的高识别度、真实清漆高光、车身折线、阴影和原图光照方向。",
    active: true,
    isDefault: true,
    sortOrder: 20,
  },
  {
    id: "default-porsche-gt-silver-metallic",
    brand: "Default",
    label: "Porsche GT Silver Metallic",
    labelZh: "保时捷 GT 银",
    labelEn: "Porsche GT Silver Metallic",
    colorCode: "",
    hex: "#A3ACB3",
    material: "metallic",
    prompt: "将车身漆面改为保时捷 GT 银 / Porsche GT Silver Metallic，保留高级干净的银色金属漆颗粒、清漆反射、车身折线和真实环境色温。",
    active: true,
    isDefault: true,
    sortOrder: 30,
  },
  {
    id: "default-nardo-gray",
    brand: "Default",
    label: "Audi Nardo Grey",
    labelZh: "奥迪纳多灰",
    labelEn: "Audi Nardo Grey",
    colorCode: "",
    hex: "#C0C6C8",
    material: "gloss",
    prompt: "将车身漆面改为奥迪纳多灰 / Audi Nardo Grey，保留改装车常见的高泛用灰色质感、原图高光、阴影、面板缝隙、车身折线和真实环境反射。",
    active: true,
    isDefault: true,
    sortOrder: 40,
  },
  {
    id: "default-gloss-black",
    brand: "Default",
    label: "Porsche Jet Black Metallic",
    labelZh: "保时捷曜石黑",
    labelEn: "Porsche Jet Black Metallic",
    colorCode: "",
    hex: "#0B0B0C",
    material: "metallic",
    prompt: "将车身漆面改为保时捷曜石黑 / Porsche Jet Black Metallic，保留深黑金属漆的高级反射、清漆高光、车身折线、阴影和原图光照方向。",
    active: true,
    isDefault: true,
    sortOrder: 50,
  },
  {
    id: "default-pearl-white",
    brand: "Default",
    label: "Lexus Eminent White Pearl",
    labelZh: "雷克萨斯珍珠白",
    labelEn: "Lexus Eminent White Pearl",
    colorCode: "",
    hex: "#F2F0EA",
    material: "pearl",
    prompt: "将车身漆面改为雷克萨斯珍珠白 / Lexus Eminent White Pearl，保留干净安全的珍珠白珠光层次、真实清漆反射、阴影和原图环境色温。",
    active: true,
    isDefault: true,
    sortOrder: 60,
  },
  {
    id: "default-british-racing-green",
    brand: "Default",
    label: "British Racing Green",
    labelZh: "英伦赛车绿",
    labelEn: "British Racing Green",
    colorCode: "",
    hex: "#004225",
    material: "gloss",
    prompt: "将车身漆面改为英伦赛车绿 / British Racing Green，保留复古跑车深绿色漆面、真实清漆高光、车身折线、阴影和原图环境反射。",
    active: true,
    isDefault: true,
    sortOrder: 70,
  },
  {
    id: "default-porsche-racing-yellow",
    brand: "Default",
    label: "Porsche Racing Yellow",
    labelZh: "保时捷竞速黄",
    labelEn: "Porsche Racing Yellow",
    colorCode: "",
    hex: "#FFD400",
    material: "gloss",
    prompt: "将车身漆面改为保时捷竞速黄 / Porsche Racing Yellow，保留高识别度亮黄色漆面、真实清漆高光、车身折线、阴影和原图光照方向。",
    active: true,
    isDefault: true,
    sortOrder: 80,
  },
  {
    id: "default-mclaren-papaya-orange",
    brand: "Default",
    label: "McLaren Papaya Orange",
    labelZh: "迈凯伦木瓜橙",
    labelEn: "McLaren Papaya Orange",
    colorCode: "",
    hex: "#FFC43D",
    material: "gloss",
    prompt: "将车身漆面改为迈凯伦木瓜橙 / McLaren Papaya Orange，保留超跑橙色的明亮视觉冲击、真实清漆高光、车身折线、阴影和原图光照方向。",
    active: true,
    isDefault: true,
    sortOrder: 90,
  },
  {
    id: "default-nissan-midnight-purple",
    brand: "Default",
    label: "Nissan Midnight Purple",
    labelZh: "日产午夜紫",
    labelEn: "Nissan Midnight Purple",
    colorCode: "",
    hex: "#2B1B3F",
    material: "metallic",
    prompt: "将车身漆面改为日产午夜紫 / Nissan Midnight Purple，保留 JDM 夜景风格深紫色金属漆层次、清漆高光、车身折线、阴影和原图环境反射。",
    active: true,
    isDefault: true,
    sortOrder: 100,
  },
  {
    id: "default-porsche-aurum",
    brand: "Default",
    label: "Porsche Aurum",
    labelZh: "保时捷 Aurum 金",
    labelEn: "Porsche Aurum",
    colorCode: "",
    hex: "#B08D57",
    material: "metallic",
    prompt: "将车身漆面改为保时捷 Aurum 金 / Porsche Aurum，保留香槟金属漆的复古豪华质感、真实清漆高光、车身折线、阴影和原图环境反射。",
    active: true,
    isDefault: true,
    sortOrder: 110,
  },
  {
    id: "bmw-isle-of-man-green-metallic",
    brand: "BMW",
    brandAliases: ["bmw", "m2", "m3", "m4", "m5", "宝马", "寶馬"],
    label: "Isle of Man Green",
    labelZh: "Isle of Man Green",
    labelEn: "Isle of Man Green",
    colorCode: "C4G",
    hex: "#1f4d3a",
    material: "metallic",
    prompt: "将车身漆面改为 BMW Isle of Man Green metallic，保留真实金属漆颗粒、清漆高光、环境反射和原图光照方向。",
    active: true,
    sortOrder: 10,
  },
  {
    id: "bmw-m-portimao-blue-metallic",
    brand: "BMW",
    brandAliases: ["bmw", "m2", "m3", "m4", "m5", "宝马", "寶馬"],
    label: "Portimao Blue",
    labelZh: "Portimao Blue",
    labelEn: "Portimao Blue",
    colorCode: "C31",
    hex: "#1b4f9c",
    material: "metallic",
    prompt: "将车身漆面改为 BMW Portimao Blue metallic，保持车身折线、金属漆层次、真实高光和原始环境反射。",
    active: true,
    sortOrder: 20,
  },
  {
    id: "bmw-sao-paulo-yellow",
    brand: "BMW",
    brandAliases: ["bmw", "m2", "m3", "m4", "m5", "宝马", "寶馬"],
    label: "Sao Paulo Yellow",
    labelZh: "Sao Paulo Yellow",
    labelEn: "Sao Paulo Yellow",
    colorCode: "C4H",
    hex: "#d7d216",
    material: "gloss",
    prompt: "将车身漆面改为 BMW Sao Paulo Yellow 亮面黄，保持清漆反射、阴影和车身钣金曲面连续。",
    active: true,
    sortOrder: 30,
  },
  {
    id: "porsche-shark-blue",
    brand: "Porsche",
    brandAliases: ["porsche", "911", "718", "cayman", "boxster", "panamera", "taycan", "保时捷", "保時捷"],
    label: "Shark Blue",
    labelZh: "Shark Blue",
    labelEn: "Shark Blue",
    colorCode: "D5C",
    hex: "#0067b1",
    material: "gloss",
    prompt: "将车身漆面改为 Porsche Shark Blue 亮面蓝，保留原图真实反射、阴影、车身折线和玻璃/灯具边界。",
    active: true,
    sortOrder: 10,
  },
  {
    id: "porsche-guards-red",
    brand: "Porsche",
    brandAliases: ["porsche", "911", "718", "cayman", "boxster", "panamera", "taycan", "保时捷", "保時捷"],
    label: "Guards Red",
    labelZh: "Guards Red",
    labelEn: "Guards Red",
    colorCode: "G1",
    hex: "#c1121f",
    material: "gloss",
    prompt: "将车身漆面改为 Porsche Guards Red 亮面红，保持真实清漆高光、环境反射和车身面板缝隙。",
    active: true,
    sortOrder: 20,
  },
  {
    id: "porsche-chalk",
    brand: "Porsche",
    brandAliases: ["porsche", "911", "718", "cayman", "boxster", "panamera", "taycan", "保时捷", "保時捷"],
    label: "Chalk",
    labelZh: "Chalk",
    labelEn: "Chalk",
    colorCode: "M9A",
    hex: "#b8b4aa",
    material: "gloss",
    prompt: "将车身漆面改为 Porsche Chalk 灰白色亮面漆，保留原图光线、阴影、清漆反射和真实色温。",
    active: true,
    sortOrder: 30,
  },
]

const refRoot = "/assets/parts/references/multi-ref-v1"

function refs(assetId: string, folder: string, files: string[], hint: string, role: PartAssetReference["role"] = "full_part_reference"): PartAssetReference[] {
  return files.map((file, index) => ({
    id: `${assetId}-ref-${index + 1}`,
    assetId,
    url: `${refRoot}/${folder}/${file}`,
    role,
    view: index === 0 ? "primary" : `reference-${index + 1}`,
    priority: index + 1,
    promptHint: hint,
    uploadToModel: true,
    active: true,
    createdAt: 0,
  }))
}

export const assetsSeed: PartAsset[] = [
  {
    id: "bbs-lmr-ds-sld",
    categoryId: "wheels",
    brandId: "brand-bbs",
    brand: "BBS",
    model: "LM-R",
    variant: "DS-SLD",
    keywords: "BBS LM-R DS-SLD, LM-R DS-SLD, DS-SLD",
    color: "Diamond Silver disk / Silver rim",
    finish: "diamond-cut silver",
    imageUrl: "/assets/parts/test-cases/bbs-lmr-ds-sld.jpg",
    active: true,
    sortOrder: 10,
    promptHint: "只安装 BBS LM-R DS-SLD 轮毂。保持轮胎直径、胎壁厚度、刹车盘深度、轮拱位置和真实金属反光。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("bbs-lmr-ds-sld", "bbs-lmr-ds-sld", ["01-exact-ds-sld.jpg", "02-lineup-hero.jpg", "03-shape-dbSld.jpg", "04-shape-dsBkbd.jpg", "05-shape-dbBkbd.jpg"], "BBS LM-R 多参考图：第一张控制准确配色和材质，后续图片只参考轮毂结构、轮唇层次和造型。"),
  },
  {
    id: "bbs-lmr-db-sld",
    categoryId: "wheels",
    brandId: "brand-bbs",
    brand: "BBS",
    model: "LM-R",
    variant: "DB-SLD",
    keywords: "BBS LM-R DB-SLD, LM-R DB-SLD, DB-SLD",
    color: "Diamond Black disk / Silver rim",
    finish: "diamond black with silver lip",
    imageUrl: "/assets/parts/test-cases/bbs-lmr-db-sld.jpg",
    active: true,
    sortOrder: 20,
    promptHint: "只安装 BBS LM-R DB-SLD 轮毂。使用钻石黑中心盘和银色抛光轮唇，保持轮毂圆形、透视和真实刹车可见关系。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("bbs-lmr-db-sld", "bbs-lmr-db-sld", ["01-exact-db-sld.jpg", "02-lineup-hero.jpg", "03-shape-dsSld.jpg", "04-shape-dsBkbd.jpg", "05-shape-dbBkbd.jpg"], "BBS LM-R DB-SLD 参考组：第一张控制配色，其余图片只参考造型和结构。"),
  },
  {
    id: "bbs-lmr-ds-bkbd",
    categoryId: "wheels",
    brandId: "brand-bbs",
    brand: "BBS",
    model: "LM-R",
    variant: "DS-BKBD",
    keywords: "BBS LM-R DS-BKBD, LM-R DS-BKBD, DS-BKBD",
    color: "Diamond Silver disk / Black Bright rim",
    finish: "silver face with black bright lip",
    imageUrl: "/assets/parts/test-cases/bbs-lmr-ds-bkbd.jpg",
    active: true,
    sortOrder: 30,
    promptHint: "只安装 BBS LM-R DS-BKBD 轮毂。保持银色盘面、亮黑轮唇、多片式螺丝、圆形几何和正确轮胎贴合关系。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("bbs-lmr-ds-bkbd", "bbs-lmr-ds-bkbd", ["01-exact-ds-bkbd.jpg", "02-lineup-hero.jpg", "03-shape-dsSld.jpg", "04-shape-dbSld.jpg", "05-shape-dbBkbd.jpg"], "BBS LM-R DS-BKBD 参考组：第一张控制材质和配色，其余图片只参考结构。"),
  },
  {
    id: "bbs-lmr-db-bkbd",
    categoryId: "wheels",
    brandId: "brand-bbs",
    brand: "BBS",
    model: "LM-R",
    variant: "DB-BKBD",
    keywords: "BBS LM-R DB-BKBD, LM-R DB-BKBD, DB-BKBD",
    color: "Diamond Black disk / Black Bright rim",
    finish: "diamond black with black bright lip",
    imageUrl: "/assets/parts/test-cases/bbs-lmr-db-bkbd.jpg",
    active: true,
    sortOrder: 40,
    promptHint: "只安装 BBS LM-R DB-BKBD 轮毂。保持钻石黑盘面、亮黑轮唇、多片式深度和前后轮正确透视。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("bbs-lmr-db-bkbd", "bbs-lmr-db-bkbd", ["01-exact-db-bkbd.jpg", "02-lineup-hero.jpg", "03-shape-dsSld.jpg", "04-shape-dbSld.jpg", "05-shape-dsBkbd.jpg"], "BBS LM-R DB-BKBD 参考组：第一张控制材质和配色，其余图片只参考结构。"),
  },
  {
    id: "brembo-gt-red",
    categoryId: "calipers",
    brandId: "brand-brembo",
    brand: "Brembo",
    model: "GT",
    variant: "Red",
    keywords: "Brembo GT Red, Brembo GT",
    color: "Racing red",
    finish: "gloss powder coat",
    imageUrl: "/assets/parts/test-cases/brembo-gt-red.jpg",
    active: true,
    sortOrder: 10,
    promptHint: "只在轮辐后方添加红色 Brembo GT 刹车卡钳。卡钳必须贴合刹车盘并被轮辐自然遮挡，不能覆盖轮毂主体造型。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("brembo-gt-red", "brembo-gt-red", ["01-red-drilled.jpg", "02-red-slotted-type-1.jpg", "03-red-slotted-type-3.jpg"], "Brembo 红色卡钳参考图：只参考安装位置、颜色和刹车盘关系。", "install_context"),
  },
  {
    id: "brembo-gt-s-6p",
    categoryId: "calipers",
    brandId: "brand-brembo",
    brand: "Brembo",
    model: "GT-S",
    variant: "6-Piston",
    keywords: "Brembo GT-S 6-Piston, Brembo GTS, Brembo GT-S",
    color: "Configurable caliper color",
    finish: "street performance brake kit",
    imageUrl: "/assets/parts/test-cases/brembo-gt-red.jpg",
    active: true,
    sortOrder: 12,
    promptHint: "Install Brembo GT-S 6-piston brake calipers behind the wheel spokes only. Preserve wheel design, tire shape, body paint, glass, lights, background, camera angle, and lighting.",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("brembo-gt-s-6p", "brembo-gt-red", ["01-red-drilled.jpg", "02-red-slotted-type-1.jpg", "03-red-slotted-type-3.jpg"], "Brembo GT-S temporary reference: use only caliper location, brake-disc relationship, and occlusion.", "install_context"),
  },
  {
    id: "brembo-gt-r-monobloc",
    categoryId: "calipers",
    brandId: "brand-brembo",
    brand: "Brembo",
    model: "GT-R",
    variant: "Monobloc",
    keywords: "Brembo GT-R Monobloc, Brembo GTR, Brembo GT-R",
    color: "Configurable caliper color",
    finish: "track monobloc brake kit",
    imageUrl: "/assets/parts/test-cases/brembo-gt-red.jpg",
    active: true,
    sortOrder: 14,
    promptHint: "Install Brembo GT-R monobloc brake calipers behind the wheel spokes only. Keep the calipers attached to the brake discs with realistic scale, shadows, and spoke occlusion.",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("brembo-gt-r-monobloc", "brembo-gt-red", ["01-red-drilled.jpg", "02-red-slotted-type-1.jpg", "03-red-slotted-type-3.jpg"], "Brembo GT-R temporary reference: use only brake caliper placement and disc relationship.", "install_context"),
  },
  {
    id: "brembo-b-m6-track",
    categoryId: "calipers",
    brandId: "brand-brembo",
    brand: "Brembo",
    model: "B-M6",
    variant: "Track",
    keywords: "Brembo B-M6 Track, Brembo BM6, Brembo B-M6",
    color: "Configurable caliper color",
    finish: "large performance brake kit",
    imageUrl: "/assets/parts/test-cases/brembo-gt-red.jpg",
    active: true,
    sortOrder: 16,
    promptHint: "Install Brembo B-M6 track brake calipers behind the wheel spokes only. Do not alter wheel design, wheel color, tires, vehicle body, glass, lights, or background.",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("brembo-b-m6-track", "brembo-gt-red", ["01-red-drilled.jpg", "02-red-slotted-type-1.jpg", "03-red-slotted-type-3.jpg"], "Brembo B-M6 temporary reference: use only caliper placement, scale, and brake-disc occlusion.", "install_context"),
  },
  {
    id: "ap-racing-yellow",
    categoryId: "calipers",
    brandId: "brand-ap-racing",
    brand: "AP Racing",
    model: "Pro 5000R",
    variant: "Yellow",
    keywords: "AP Racing Pro 5000R Yellow, AP Racing Pro 5000R, Pro 5000R",
    color: "Track yellow",
    finish: "gloss powder coat",
    imageUrl: "/assets/parts/test-cases/ap-racing-pro-5000r.jpg",
    active: true,
    sortOrder: 20,
    promptHint: "在可见轮辐后方添加黄色 AP Racing Pro 5000R 刹车卡钳。比例、安装角度和遮挡关系必须符合轮毂与刹车盘透视。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("ap-racing-yellow", "ap-racing-yellow", ["01-banner-12-source.jpg", "02-banner-5-page.jpg", "03-pro-5000-r-section.jpg"], "AP Racing 黄色卡钳参考图：只参考颜色、卡钳轮廓和安装关系。", "install_context"),
  },
  {
    id: "m-performance-carbon-wing",
    categoryId: "rear-wing",
    brandId: "brand-m-performance",
    brand: "M Performance",
    model: "Carbon GT Wing",
    variant: "Medium",
    keywords: "M Performance Carbon GT Wing, Carbon GT Wing",
    color: "Carbon black",
    finish: "visible carbon fiber",
    imageUrl: "/assets/parts/test-cases/rsc-f80-rear-spoiler.webp",
    active: true,
    sortOrder: 10,
    promptHint: "只在后备箱合理位置安装中等尺寸碳纤维尾翼。匹配后备箱透视和安装点，不改变尾灯、后保险杠、车牌或背景。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "side"],
    generationReferences: refs("m-performance-carbon-wing", "m-performance-carbon-wing", ["01-rear2.jpg", "02-angle-2.jpg", "03-angle-3.jpg"], "尾翼参考组：只参考安装宽度、高度、支架关系和碳纤维材质。"),
  },
  {
    id: "f82-m4-kies-carbon-trunk-lip-spoiler",
    categoryId: "rear-wing",
    brandId: "brand-kies",
    brand: "Kies Motorsports",
    model: "Carbon Trunk Lip Spoiler",
    variant: "F82 M4",
    keywords: "Kies Carbon Trunk Lip Spoiler, F82 M4 Carbon Trunk Lip Spoiler",
    color: "Carbon black",
    finish: "visible carbon fiber",
    imageUrl: "/assets/parts/test-cases/f82-m4-kies-carbon-trunk-lip-spoiler.jpg",
    active: true,
    sortOrder: 20,
    promptHint: "只沿后备箱上沿安装低矮碳纤维 trunk lip spoiler。保持薄而连续、贴合可见后备箱弧线，不要变成高脚大尾翼。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "side"],
    generationReferences: refs("f82-m4-kies-carbon-trunk-lip-spoiler", "f82-m4-kies-carbon-trunk-lip-spoiler", ["01-kies-main.jpg", "02-kies-angle.jpg", "03-kies-detail.jpg"], "F82 M4 trunk lip 多角度参考图：只参考低矮连续 lip 的宽度、厚度、弧线、上翘幅度、贴合边缘和碳纤维材质。"),
  },
  {
    id: "varis-front-lip",
    categoryId: "front-bumper",
    brandId: "brand-varis",
    brand: "Varis",
    model: "Carbon Front Lip",
    variant: "Street",
    keywords: "Varis Carbon Front Lip, Carbon Front Lip",
    color: "Carbon black",
    finish: "visible carbon fiber",
    imageUrl: "/assets/parts/test-cases/apr-f80-front-splitter.webp",
    active: true,
    sortOrder: 10,
    promptHint: "只在前保险杠下沿添加碳纤维前唇/前铲。保留原车进气口、中网、大灯、地面阴影和相机角度。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "front"],
    generationReferences: refs("varis-front-lip", "varis-front-lip", ["01-product-main.jpg", "02-installed-front.jpg", "03-product-angle-8.jpg", "04-product-angle-6.jpg", "05-installed-front-7.jpg"], "前唇多参考图：产品图参考形状，安装图只参考前杠下沿贴合位置，不继承背景或整车。"),
  },
  {
    id: "rsc-f80-side-skirts",
    categoryId: "side-skirts",
    brandId: "brand-rsc",
    brand: "RSC",
    model: "F80 Side Skirts",
    variant: "Carbon",
    keywords: "RSCBMW001, RSC F80 Side Skirts, F80 Side Skirts",
    color: "Carbon black",
    finish: "visible carbon fiber",
    imageUrl: "/assets/parts/test-cases/rsc-f80-side-skirts.webp",
    active: true,
    sortOrder: 10,
    promptHint: "只沿左右门槛下沿安装碳纤维侧裙延伸件。跟随原图透视，不改变车门、轮毂、后视镜或车身颜色。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["side", "rear_three_quarter", "front_three_quarter"],
    generationReferences: refs("rsc-f80-side-skirts", "rsc-f80-side-skirts", ["01-side-skirt-6.jpg", "02-side-skirt-3.jpg", "03-side-skirt-5.jpg", "04-side-skirt-2.jpg", "05-side-skirt-4.jpg", "06-side-skirt-7.jpg"], "侧裙参考组：只参考门槛线安装位置、长度、碳纤维边缘厚度和接触阴影。"),
  },
  {
    id: "rsc-f80-carbon-diffuser",
    categoryId: "diffuser",
    brandId: "brand-rsc-diffuser",
    brand: "RSC",
    model: "F80 Carbon Diffuser",
    variant: "Aggressive",
    keywords: "RSC F80 Carbon Diffuser, F80 Carbon Diffuser",
    color: "Carbon black",
    finish: "visible carbon fiber",
    imageUrl: "/assets/parts/test-cases/rsc-f80-carbon-diffuser.webp",
    active: true,
    sortOrder: 10,
    promptHint: "只在后保险杠下方安装碳纤维扩散器。保留排气开口、尾灯、车牌区域、保险杠主体形状和真实地面阴影。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
    generationReferences: refs("rsc-f80-carbon-diffuser", "rsc-f80-carbon-diffuser", ["01-product-square.jpg", "02-installed-dsc08708.jpg", "03-installed-close.jpg", "04-installed-green-rear.jpg", "05-installed-violet-rear.jpg", "06-product-diffuser1.png"], "后扩散器参考组：只参考鳍片几何、后杠贴合关系和碳纤维材质，不继承参考车背景。"),
  },
  {
    id: "akrapovic-quad-tip",
    categoryId: "exhaust",
    brandId: "brand-akrapovic",
    brand: "Akrapovic",
    model: "Quad Tip",
    variant: "Titanium",
    keywords: "Akrapovic Quad Tip, Akrapovic Titanium Quad Tip",
    color: "Burnt titanium",
    finish: "brushed titanium",
    imageUrl: "/assets/parts/test-cases/akrapovic-tail-pipe-carbon.jpg",
    active: true,
    sortOrder: 10,
    promptHint: "只在后保险杠排气开口处安装四出钛合金尾嘴。尾嘴必须对齐原有开口，保持保险杠、扩散器、车牌和尾灯不变。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
    generationReferences: refs("akrapovic-quad-tip", "akrapovic-quad-tip", ["01-tail-pipe-product.jpg", "02-tail-pipe-angle.jpg", "03-tail-pipe-detail.jpg"], "Akrapovic 尾嘴参考图：只参考金属材质、出口形状和后杠安装关系。"),
  },
  {
    id: "seibon-oe-carbon-hood",
    categoryId: "hood",
    brandId: "brand-seibon",
    brand: "Seibon",
    model: "OE Carbon Hood",
    variant: "F80/F82",
    keywords: "HD14BMWF80-OE, Seibon OE Carbon Hood, Seibon OE-Style Carbon Fiber Hood",
    color: "Carbon black",
    finish: "visible carbon fiber",
    imageUrl: "/assets/parts/test-cases/seibon-oe-carbon-hood.jpg",
    active: true,
    sortOrder: 10,
    promptHint: "只替换 Seibon OE-style 机盖面板。默认按原车车身同色喷漆；只有 colorPolicy 为 exposed_carbon 时，才在机盖表面显示裸露碳纤维纹理，且不能扩散到其它部位。",
    defaultColorPolicy: "body_color",
    allowedColorPolicies: ["body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "front", "side"],
    generationReferences: refs("seibon-oe-carbon-hood", "seibon-oe-carbon-hood", ["01-hd14bmwf80-oe-01.jpg", "02-hd14bmwf80-oe-02.jpg", "03-hd14bmwf80-oe-03.jpg", "04-hd14bmwf80-oe-04.jpg", "05-hd14bmwf80-oe-05.jpg", "06-hd14bmwf80-oe-07.jpg", "07-hd14bmwf80-oe-08.jpg"], "Seibon OE 机盖多角度参考图：只参考机盖边界、左右折线、中央 power dome、曲面高低关系、前沿/后沿比例和安装贴合关系。"),
  },
  {
    id: "vland-f80-smoked-tail-lights",
    categoryId: "lights",
    brandId: "brand-vland",
    brand: "VLAND",
    model: "F80 Smoked Tail Lights",
    variant: "Smoked",
    keywords: "VLAND F80 Smoked Tail Lights, F80 Smoked Tail Lights",
    color: "smoked red lens",
    finish: "gloss smoked lens",
    imageUrl: "/assets/parts/test-cases/vland-f80-smoked-tail-lights.webp",
    active: true,
    sortOrder: 10,
    promptHint: "只对可见尾灯应用烟熏灯罩效果。保留灯具外轮廓、后备箱、保险杠、车牌和周围钣金不变。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
    generationReferences: refs("vland-f80-smoked-tail-lights", "vland-f80-smoked-tail-lights", ["01-smoked-1.webp", "02-smoked-2.webp", "03-smoked-3.webp", "04-smoked-4.webp", "05-smoked-5.webp", "06-smoked-6.webp", "07-smoked-7.webp"], "烟熏尾灯参考图：只参考灯罩色调、透明度和原厂灯具外轮廓。", "material_reference"),
  },
  {
    id: "bmw-m-performance-black-grille",
    categoryId: "grille",
    brandId: "brand-bmw-m-performance",
    brand: "BMW M Performance",
    model: "Gloss Black Kidney Grille",
    variant: "F80/F82",
    keywords: "BMW M Performance Gloss Black Kidney Grille, Gloss Black Kidney Grille",
    color: "gloss black",
    finish: "gloss black plastic",
    imageUrl: "/assets/parts/test-cases/bmw-m-performance-gloss-black-grille.webp",
    active: true,
    sortOrder: 10,
    promptHint: "只把双肾中网替换为亮黑款式。保留前保险杠、大灯、机盖缝线、前车牌和原图反射。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "front"],
    generationReferences: refs("bmw-m-performance-black-grille", "bmw-m-performance-black-grille", ["01-grille-main.jpg", "02-grille-2.jpg", "03-grille-3.jpg", "04-grille-4.jpg", "05-grille-5.jpg", "06-grille-6.jpg"], "亮黑双肾中网参考图：只参考中网纹理、外轮廓和亮黑材质。"),
  },
  {
    id: "carbon-mirror-caps",
    categoryId: "mirrors",
    brandId: "brand-oem-plus",
    brand: "OEM+",
    model: "Mirror Caps",
    variant: "Carbon",
    keywords: "Carbon Mirror Caps, Mirror Caps",
    color: "Carbon black",
    finish: "visible carbon fiber",
    imageUrl: "/assets/parts/test-cases/apr-formula-gt3-mirror.webp",
    active: true,
    sortOrder: 10,
    promptHint: "只替换后视镜外壳为可见碳纤维镜盖。保留后视镜形状、镜片、支架、车门、车窗和原图反射。",
    defaultColorPolicy: "body_color",
    allowedColorPolicies: ["body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
    generationReferences: refs("carbon-mirror-caps", "carbon-mirror-caps", ["01-apr-official.jpg", "02-map-angle-1.jpg", "03-map-angle-2.jpg", "04-map-angle-3.jpg", "05-map-angle-4.jpg"], "碳纤维后视镜盖参考图：只参考镜盖纹理、外壳形状和安装边界。"),
  },
  {
    id: "3m-2080-s261-satin-dark-gray",
    categoryId: "wrap",
    brandId: "brand-3m",
    brand: "3M",
    model: "2080 S261",
    variant: "Satin Dark Gray",
    keywords: "3M 2080 S261, 2080 S261 Satin Dark Gray, Satin Dark Gray",
    color: "satin dark gray",
    finish: "satin wrap",
    imageUrl: "/assets/parts/test-cases/3m-2080-s261-satin-dark-gray.avif",
    active: true,
    sortOrder: 10,
    promptHint: "只把车身漆面改为 3M Satin Dark Gray 缎面深灰。保留所有饰条、玻璃、轮毂、灯具、碳纤维件、贴纸和原图光照。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side", "rear_three_quarter"],
    generationReferences: refs("3m-2080-s261-satin-dark-gray", "3m-2080-s261-satin-dark-gray", ["01-exact-swatch.jpg", "02-exact-swatch-506.jpg", "03-2080-color-poster.jpg"], "3M 缎面深灰色卡参考图：只作为车身漆面材质和颜色参考。", "material_reference"),
  },
  {
    id: "wing-ducktail",
    categoryId: "rear-wing",
    brandId: "brand-wing-style",
    brand: "Style Library",
    model: "Ducktail",
    variant: "鸭尾",
    keywords: "ducktail, duck tail, 鸭尾, trunk edge spoiler, low rear spoiler",
    color: "configurable",
    finish: "black, carbon fiber, or body color",
    imageUrl: "/assets/parts/test-cases/f82-m4-kies-carbon-trunk-lip-spoiler.jpg",
    active: true,
    sortOrder: 100,
    promptHint: "安装鸭尾：贴着后备箱或尾门边缘微微上翘，造型低调，只改善车尾上沿视觉运动感。不要生成高脚尾翼或外露支架。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color", "body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "side"],
  },
  {
    id: "wing-lip-spoiler",
    categoryId: "rear-wing",
    brandId: "brand-wing-style",
    brand: "Style Library",
    model: "Lip Spoiler",
    variant: "小尾翼",
    keywords: "lip spoiler, trunk lip, 小尾翼, thin spoiler, oem sport spoiler",
    color: "configurable",
    finish: "black, carbon fiber, or body color",
    imageUrl: "/assets/parts/test-cases/f82-m4-kies-carbon-trunk-lip-spoiler.jpg",
    active: true,
    sortOrder: 110,
    promptHint: "安装小尾翼 / Lip Spoiler：薄片式贴合后备箱上沿，比鸭尾更薄更原厂，装饰属性强，不能夸张或变成 GT wing。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color", "body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "side"],
  },
  {
    id: "wing-gt-wing",
    categoryId: "rear-wing",
    brandId: "brand-wing-style",
    brand: "Style Library",
    model: "GT Wing",
    variant: "高脚尾翼",
    keywords: "gt wing, high mount wing, 高脚尾翼, racing wing",
    color: "configurable",
    finish: "black, carbon fiber, or body color",
    imageUrl: "/assets/parts/test-cases/rsc-f80-rear-spoiler.webp",
    active: true,
    sortOrder: 120,
    promptHint: "安装高脚尾翼 / GT Wing：翼面与车身分离并有支架，偏赛道风格。支架位置、翼面宽度、高度和角度必须真实贴合车尾。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color", "body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "side"],
  },
  {
    id: "wing-swan-neck",
    categoryId: "rear-wing",
    brandId: "brand-wing-style",
    brand: "Style Library",
    model: "Swan Neck",
    variant: "天鹅颈尾翼",
    keywords: "swan neck wing, swan-neck spoiler, 天鹅颈尾翼, top mount wing",
    color: "configurable",
    finish: "black, carbon fiber, or body color",
    imageUrl: "/assets/parts/test-cases/rsc-f80-rear-spoiler.webp",
    active: true,
    sortOrder: 130,
    promptHint: "安装 Swan Neck / 天鹅颈尾翼：支架从翼面上方连接，翼面下方保持干净气流造型，视觉更赛车化但不能重画车尾。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color", "body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "side"],
  },
  {
    id: "wing-time-attack",
    categoryId: "rear-wing",
    brandId: "brand-wing-style",
    brand: "Style Library",
    model: "Time Attack Wing",
    variant: "双层尾翼",
    keywords: "time attack wing, double wing, dual element wing, 双层尾翼, 双层扰流板",
    color: "configurable",
    finish: "black, carbon fiber, or body color",
    imageUrl: "/assets/parts/test-cases/rsc-f80-rear-spoiler.webp",
    active: true,
    sortOrder: 140,
    promptHint: "安装双层尾翼 / Time Attack Wing：主翼加副翼或上下双层结构，下压力视觉更强，但必须只作用于尾翼区域。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color", "body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "side"],
  },
  {
    id: "front-splitter-style",
    categoryId: "front-bumper",
    brandId: "brand-front-splitter-style",
    brand: "Style Library",
    model: "Front splitter",
    variant: "前铲",
    keywords: "front splitter, front lip, 前铲, 前唇, front blade",
    color: "configurable",
    finish: "black, carbon fiber, or body color",
    imageUrl: "/assets/parts/test-cases/apr-f80-front-splitter.webp",
    active: true,
    sortOrder: 100,
    promptHint: "只在原车前保险杠下沿添加前铲/前唇。按选择的颜色材质处理，保留大灯、中网、进气口、车牌、地面和车头轮廓。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color", "body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "front"],
  },
  {
    id: "side-skirts-style",
    categoryId: "side-skirts",
    brandId: "brand-side-skirt-style",
    brand: "Style Library",
    model: "Side skirts",
    variant: "侧裙",
    keywords: "side skirts, side skirt, 侧裙, 门槛延伸, rocker blade",
    color: "configurable",
    finish: "black, carbon fiber, or body color",
    imageUrl: "/assets/parts/test-cases/rsc-f80-side-skirts.webp",
    active: true,
    sortOrder: 100,
    promptHint: "只沿左右门槛下沿添加侧裙。按选择的颜色材质处理，保持车门缝、轮拱、车身长度、地面阴影和原图透视。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color", "body_color", "exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side", "rear_three_quarter"],
  },
  {
    id: "exhaust-single-left",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Single left",
    variant: "单边单出",
    keywords: "single left exhaust, single side single outlet, 单边单出, 左侧单出",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-single-left.svg",
    active: true,
    sortOrder: 100,
    promptHint: "排气布局改为单边单出：仅在车辆左后侧合理开口出现一根尾喉，保留尾灯、车牌、后杠主体和背景。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-single-right",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Single right",
    variant: "单边单出（右）",
    keywords: "single right exhaust, single side single outlet right, 单边单出右, 单边单出（右）",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-single-right.svg",
    active: true,
    sortOrder: 105,
    promptHint: "排气布局改为单边单出（右）：仅在车辆右后侧合理开口出现一根尾喉，不能左右都出，保留尾灯、车牌、后杠主体和背景。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-dual-left",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Dual left",
    variant: "单边双出（左）",
    keywords: "dual left exhaust, single side dual outlet left, 单边双出左, 单边双出（左）",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-dual-left.svg",
    active: true,
    sortOrder: 110,
    promptHint: "排气布局改为单边双出（左）：只在车辆左后侧并排出现两根尾喉，数量、间距和开口位置必须合理。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-dual-right",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Dual right",
    variant: "单边双出（右）",
    keywords: "dual right exhaust, single side dual outlet right, 单边双出右, 单边双出（右）",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-dual-right.svg",
    active: true,
    sortOrder: 120,
    promptHint: "排气布局改为单边双出（右）：只在车辆右后侧并排出现两根尾喉，不能左右都出，也不能改变尾灯和车牌。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-quad",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Dual side dual",
    variant: "双边双出",
    keywords: "quad exhaust, dual side quad outlet, 双边双出, 双边四出, 四出排气",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-quad.svg",
    active: true,
    sortOrder: 130,
    promptHint: "排气布局改为双边双出：左右两侧各两根尾喉，必须对称、贴合后杠开口，并保留后包围主体结构。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-dual-single",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Dual single",
    variant: "双边单出",
    keywords: "dual single exhaust, one outlet each side, 双边单出",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-dual-single.svg",
    active: true,
    sortOrder: 140,
    promptHint: "排气布局改为双边单出：左右两侧各一根尾喉，保持左右对称和真实金属内腔暗部。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-center-single",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Center single",
    variant: "居中单管",
    keywords: "center single exhaust, center exit single, 居中单管, 中置单出",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-center-single.svg",
    active: true,
    sortOrder: 150,
    promptHint: "排气布局改为居中单管：车尾中央只出现一根尾喉，保持后杠、扩散器、车牌和尾灯不变。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-center-dual",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Center dual",
    variant: "居中双管",
    keywords: "center dual exhaust, center exit dual, 居中双管, 中置双出",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-center-dual.svg",
    active: true,
    sortOrder: 160,
    promptHint: "排气布局改为居中双管：车尾中央并排两根尾喉，数量和位置必须清楚，不能变成左右两侧排气。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "exhaust-center-quad",
    categoryId: "exhaust",
    brandId: "brand-exhaust-layout",
    brand: "Layout Library",
    model: "Center quad",
    variant: "居中四管",
    keywords: "center quad exhaust, center exit quad, 居中四管, 中置四出",
    color: "metal",
    finish: "brushed stainless",
    imageUrl: "/assets/parts/test-cases/exhaust-layout-center-quad.svg",
    active: true,
    sortOrder: 170,
    promptHint: "排气布局改为居中四管：车尾中央四根尾喉紧凑排列，保留尾灯、车牌、后杠主体和相机角度。",
    defaultColorPolicy: "part_reference_color",
    allowedColorPolicies: ["part_reference_color"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
  {
    id: "dry-carbon-hood",
    categoryId: "hood",
    brandId: "brand-dry-carbon-hood",
    brand: "Dry Carbon",
    model: "Hood",
    variant: "机盖裸碳",
    keywords: "dry carbon hood, exposed carbon hood, 机盖裸碳, 碳纤维机盖",
    color: "exposed carbon",
    finish: "dry carbon fiber",
    imageUrl: "/assets/parts/test-cases/seibon-oe-carbon-hood.jpg",
    active: true,
    sortOrder: 100,
    promptHint: "只将机盖面板改为裸露干碳纤维材质。不能把碳纤维纹理扩散到车顶、翼子板、保险杠、后视镜、车门或灯具。",
    defaultColorPolicy: "exposed_carbon",
    allowedColorPolicies: ["exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "front"],
  },
  {
    id: "dry-carbon-mirrors",
    categoryId: "mirrors",
    brandId: "brand-dry-carbon-mirrors",
    brand: "Dry Carbon",
    model: "Mirror caps",
    variant: "后视镜裸碳",
    keywords: "dry carbon mirrors, exposed carbon mirror caps, 后视镜裸碳, 镜壳裸碳",
    color: "exposed carbon",
    finish: "dry carbon fiber",
    imageUrl: "/assets/parts/test-cases/apr-formula-gt3-mirror.webp",
    active: true,
    sortOrder: 100,
    promptHint: "只将后视镜外壳/镜盖改为裸露干碳纤维材质。保留镜片、支架、车门连接、角度和反射。",
    defaultColorPolicy: "exposed_carbon",
    allowedColorPolicies: ["exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
  },
  {
    id: "dry-carbon-fenders",
    categoryId: "fenders",
    brandId: "brand-dry-carbon-fenders",
    brand: "Dry Carbon",
    model: "Fenders",
    variant: "叶子板裸碳",
    keywords: "dry carbon fenders, exposed carbon fenders, 叶子板裸碳, 翼子板裸碳",
    color: "exposed carbon",
    finish: "dry carbon fiber",
    imageUrl: "/assets/parts/test-cases/seibon-oe-carbon-hood.jpg",
    active: true,
    sortOrder: 100,
    promptHint: "只将可见叶子板/翼子板区域改为裸露干碳纤维材质。必须保留轮拱形状、门缝、机盖缝、车灯边界和车身比例。",
    defaultColorPolicy: "exposed_carbon",
    allowedColorPolicies: ["exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["front_three_quarter", "side"],
  },
  {
    id: "dry-carbon-trunk-lid",
    categoryId: "trunk-lid",
    brandId: "brand-dry-carbon-trunk",
    brand: "Dry Carbon",
    model: "Trunk lid",
    variant: "后备箱盖裸碳",
    keywords: "dry carbon trunk lid, exposed carbon trunk lid, 后备箱盖裸碳, 尾箱盖裸碳",
    color: "exposed carbon",
    finish: "dry carbon fiber",
    imageUrl: "/assets/parts/test-cases/f82-m4-kies-carbon-trunk-lip-spoiler.jpg",
    active: true,
    sortOrder: 100,
    promptHint: "只将后备箱盖/尾门盖板改为裸露干碳纤维材质。保留尾灯、车牌、后杠、尾翼和周围钣金缝隙。",
    defaultColorPolicy: "exposed_carbon",
    allowedColorPolicies: ["exposed_carbon"],
    generationReady: true,
    promptTestStatus: "pass",
    recommendedViews: ["rear_three_quarter", "rear"],
  },
]

export const promptSeed: PromptPreset = {
  id: "preset_oem_plus_v1",
  title: "Effective Prompt v1 中文有效版",
  version: "3.0-effective-v1",
  active: true,
  createdAt: 0,
  body:
    "请对第一张上传的原车照片做真实照片局部编辑。第一张图片是唯一原车画布；后面的图片都是配件参考图，不是车身参考，不是场景参考，不是画布。\n\n绝对保留原图：背景、地面、墙面、车位线、其它车辆、室内/室外环境、光线方向、反射、阴影、相机角度、裁切范围、车辆位置、车身比例、车牌位置和形状、玻璃、灯组、轮毂、轮胎、黑色塑料饰条、碳纤维件、进气格栅、尾翼和未选择的原厂部件。\n\n参考配件图的优先级低于原车图和后台配置。参考图只用于理解选中配件的局部形状、材质和安装位置，不继承参考图的背景、场景、整车、轮毂、颜色、文字、水印、人物、包装或展示台。\n\n如果某张配件参考图质量低、角度不适合、包含其它车辆、或与当前车辆视角不匹配，宁可忽略这张参考图，也不要改变原车、背景、车型、轮毂或未选择类别。",
  negativePrompt:
    "不要重新生成整车，不要换背景，不要换场景，不要换停车场，不要换道路，不要换墙面，不要换光线，不要换相机角度，不要换裁切，不要换车辆位置，不要换车型，不要改变车身比例，不要改变车顶线，不要改变窗线，不要改变轮拱形状，不要改变未选择轮毂，不要把轮毂改成 BBS，不要改变轮胎，不要添加未选择配件，不要添加大尾翼，不要改变未选择尾翼，不要添加排气，不要改变尾灯，不要改变后视镜，不要复制参考图背景，不要复制参考图里的其它车辆，不要复制参考图文字，不要水印，不要人物，不要展厅广告图，不要户外新场景，不要黑色机盖，除非明确要求裸露碳纤维机盖，不要让车身颜色污染玻璃、灯组、轮毂、轮胎、车牌、黑色塑料饰条、碳纤维件、进气格栅、尾翼、背景或地面。",
}

export const promptTemplateSeed: Array<Omit<PromptTemplate, "updatedAt">> = [
  {
    id: "tpl_base_photo_edit",
    scope: "base",
    title: "通用基础 Prompt - 唯一画布与参考图角色",
    body:
      "任务类型：真实照片局部编辑。第一张原车照片是唯一画布，所有输出必须看起来像在这张原图上做局部修图。必须保留原图背景、地面、墙面、车位线、其它车辆、光线方向、反射、阴影、相机角度、裁切范围、车辆位置、车身比例、车牌位置和形状、玻璃、灯组、轮毂、轮胎、黑色塑料饰条、碳纤维件、进气格栅、尾翼和未选择部件。后续图片全部是配件参考图，不是画布，不是车身参考，不是场景参考。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 5,
  },
  {
    id: "tpl_config_mode_default",
    scope: "config_mode",
    title: "配置模式 Prompt - 后台配置最高优先级",
    body:
      "本次生图以后台配置 JSON 为最高优先级。只允许执行 JSON 中明确选择的 paint、stance、parts 和 colorPolicy 分支。没有出现在 JSON parts 中的配件绝对不要出现；同一类别只执行当前选择的一个配件。不要根据常见改装审美额外添加未选择内容。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 10,
  },
  {
    id: "tpl_chat_mode_default",
    scope: "chat_mode",
    title: "对话模式 Prompt - 用户请求转局部编辑",
    body:
      "本次生图来自用户自然语言需求。请只执行用户明确要求的改装项，保持请求范围尽量小。若用户上传配件参考图，第一张仍是唯一原车画布，后续图片只用于对应配件的造型、材质、比例和安装意图。若用户提到机盖裸碳、露碳、碳纤维机盖、exposed carbon 或 carbon hood，机盖 colorPolicy 为 exposed_carbon；否则机盖默认 body_color。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 10,
  },
  {
    id: "tpl_config_base_default",
    scope: "config_base",
    title: "配置模式基础 Prompt - 白名单",
    body:
      "前台 UI 选择就是本次允许编辑的白名单。如果某个类别没有被选择，必须保持原图不变。未选择轮毂时，轮毂款式、颜色、尺寸、辐条数量、轮唇、中心盖、轮胎和接地关系必须完全保持原图。未选择卡钳时，不要改变卡钳颜色或刹车盘。未选择尾翼、排气、后视镜、前铲、侧裙、机盖、叶子板或后备箱盖时，不要生成或替换这些部件。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 12,
  },
  {
    id: "tpl_category_wheels",
    scope: "category",
    title: "分类 Prompt - 轮毂",
    body: "轮毂改装必须保持轮子圆形不变，不能椭圆、扭曲或断裂。轮毂中心必须对准原车轮心，大小要符合原车轮拱和轮胎比例。保留真实轮胎侧壁、刹车盘深度、轮辐透视、地面接触阴影和金属反光。未选择车高时不要改变姿态。",
    assetId: "",
    combinationKey: "wheels",
    active: true,
    sortOrder: 10,
  },
  {
    id: "tpl_category_calipers",
    scope: "category",
    title: "分类 Prompt - 刹车卡钳",
    body: "刹车卡钳必须位于轮辐后方并贴合刹车盘，不能漂浮在轮毂表面，也不能盖住轮毂主体造型。只允许修改轮辐后方可见的卡钳颜色和标准 JSON 指定的刹车盘类型，不要改变轮毂款式、轮胎、车身、车高或背景。加大刹车盘要体现更大的盘面直径和合理间隙；碳陶瓷刹车盘要体现更浅的陶瓷盘面和真实金属/陶瓷层次。",
    assetId: "",
    combinationKey: "calipers",
    active: true,
    sortOrder: 20,
  },
  {
    id: "tpl_category_rear_wing",
    scope: "category",
    title: "分类 Prompt - 尾翼 / 后扰流",
    body: "尾翼只能按标准 JSON 的固定分类安装：鸭尾、小尾翼/Lip Spoiler、高脚尾翼/GT Wing、Swan Neck/天鹅颈或双层尾翼/Time Attack。必须安装在第一张原图可见的后备箱上沿、尾箱盖或原厂扰流区域，按指定黑色、碳纤维或车身同色处理。不要把低调鸭尾/小尾翼做成高脚尾翼，也不要改变尾灯、车牌、排气、后杠、相机角度或背景。",
    assetId: "",
    combinationKey: "rear-wing",
    active: true,
    sortOrder: 30,
  },
  {
    id: "tpl_category_front_bumper",
    scope: "category",
    title: "分类 Prompt - 前唇 / 前包围",
    body: "前铲只按有/无选择安装在原车前保险杠下沿，并按标准 JSON 指定的黑色、碳纤维或车身同色处理。保留原车大灯、中网、进气口、车牌区域、机盖线和车头基础轮廓。前铲离地高度、投影阴影和材质反光要真实，不能生成夸张赛车包围。",
    assetId: "",
    combinationKey: "front-bumper",
    active: true,
    sortOrder: 40,
  },
  {
    id: "tpl_category_side_skirts",
    scope: "category",
    title: "分类 Prompt - 侧裙",
    body: "侧裙只按有/无选择沿车身下侧门槛自然延伸，并按标准 JSON 指定的黑色、碳纤维或车身同色处理。必须与前后轮拱衔接顺畅，保持车门缝隙、侧面反光和原图透视，不能让侧裙穿入地面、遮挡轮胎或改变车身长度。",
    assetId: "",
    combinationKey: "side-skirts",
    active: true,
    sortOrder: 50,
  },
  {
    id: "tpl_category_diffuser",
    scope: "category",
    title: "分类 Prompt - 后扩散器",
    body: "后扩散器必须安装在后保险杠下方，鳍片方向、深度和阴影要符合原图透视。不能改变尾灯、后备箱、车牌区域和排气位置。扩散器应增强车尾层次，而不是重画整个车尾。",
    assetId: "",
    combinationKey: "diffuser",
    active: true,
    sortOrder: 60,
  },
  {
    id: "tpl_category_exhaust",
    scope: "category",
    title: "分类 Prompt - 排气",
    body: "排气必须严格执行标准 JSON 的固定布局：单边单出、单边双出（左）、单边双出（右）、双边双出、双边单出、居中单管、居中双管或居中四管。尾喉必须出现在车尾后包围合理开口位置，数量、左右位置、对称关系、金属材质和内腔暗部要真实。不要改变整个后包围结构、尾灯、车牌、相机角度或背景。",
    assetId: "",
    combinationKey: "exhaust",
    active: true,
    sortOrder: 70,
  },
  {
    id: "tpl_category_hood",
    scope: "category",
    title: "分类 Prompt - 机盖",
    body:
      "机盖改装只能作用于前保险杠、翼子板、前挡风玻璃和大灯缝线之间的机盖面板。必须保持第一张原车机盖安装边界、前沿、后沿、左右缝隙、灯眉关系和中央 power dome 的位置、宽度、高度。body_color 表示机盖必须喷成第一张原车相同车身漆，不要露出黑色碳纤维纹理；exposed_carbon 表示只在机盖表面显示裸露碳纤维纹理，不能扩散到车顶、后备箱、车门、保险杠、后视镜、轮毂或灯具。",
    assetId: "",
    combinationKey: "hood",
    active: true,
    sortOrder: 80,
  },
  {
    id: "tpl_category_lights",
    scope: "category",
    title: "分类 Prompt - 灯具 / 灯膜",
    body: "灯膜或灯具处理只能改变可见灯罩色调、透明度或细节，不得改变大灯/尾灯外轮廓、内部灯组结构和位置。烟熏效果要保留灯具玻璃反光和边缘高光，不能把灯完全涂黑或生成错误灯型。",
    assetId: "",
    combinationKey: "lights",
    active: true,
    sortOrder: 90,
  },
  {
    id: "tpl_category_wrap",
    scope: "category",
    title: "分类 Prompt - 改色 / 贴膜",
    body: "车身改色或贴膜只能作用于车身漆面板件，不能改变玻璃、灯具、轮毂、轮胎、牌照区域、黑色塑料饰条、碳纤维件、进气格栅和尾翼。必须保留原图高光、阴影、反射、车身折线和环境色温。",
    assetId: "",
    combinationKey: "wrap",
    active: true,
    sortOrder: 100,
  },
  {
    id: "tpl_category_mirrors",
    scope: "category",
    title: "分类 Prompt - 后视镜",
    body: "后视镜改装只修改后视镜外壳或镜盖材质；本轮只支持裸露干碳纤维开关。必须保留原后视镜形状、角度、镜片位置、边缘缝隙和车门连接结构。碳纤维纹理要细腻，不能让后视镜变形或消失。",
    assetId: "",
    combinationKey: "mirrors",
    active: true,
    sortOrder: 110,
  },
  {
    id: "tpl_category_fenders",
    scope: "category",
    title: "分类 Prompt - 叶子板",
    body: "叶子板/翼子板改装只支持裸露干碳纤维材质。只修改标准 JSON 指定的可见叶子板区域，必须保留轮拱形状、门缝、机盖缝、车灯边界、轮毂、轮胎和车身比例。不要把碳纤维纹理扩散到车门、机盖、保险杠、车顶或背景。",
    assetId: "",
    combinationKey: "fenders",
    active: true,
    sortOrder: 115,
  },
  {
    id: "tpl_category_trunk_lid",
    scope: "category",
    title: "分类 Prompt - 后备箱盖",
    body: "后备箱盖/尾门盖板改装只支持裸露干碳纤维材质。只修改标准 JSON 指定的后备箱盖区域，必须保留尾灯、车牌、后杠、尾翼、排气和周围钣金缝隙。不要让碳纤维纹理扩散到车顶、后翼子板、保险杠或背景。",
    assetId: "",
    combinationKey: "trunk-lid",
    active: true,
    sortOrder: 116,
  },
  {
    id: "tpl_category_grille",
    scope: "category",
    title: "分类 Prompt - 中网 / 格栅",
    body: "中网或格栅改装必须保留原车前脸比例、大灯位置、保险杠轮廓和品牌车型识别。只调整格栅内部样式、颜色或材质，不得重画整个车头，不得改变车标位置和进气口透视。",
    assetId: "",
    combinationKey: "grille",
    active: true,
    sortOrder: 120,
  },
  {
    id: "tpl_combo_wheel_stance",
    scope: "combo",
    title: "组合 Prompt - 轮毂 + 降低车高",
    body: "同时选择轮毂和降低车高时，轮心位置必须合理，轮胎与轮拱关系要真实。除非 stance 明确为激进贴地，否则不要让轮胎穿进翼子板或地面。",
    assetId: "",
    combinationKey: "wheels,stance_lowered",
    active: true,
    sortOrder: 20,
  },
  {
    id: "tpl_combo_wheel_caliper",
    scope: "combo",
    title: "组合 Prompt - 轮毂 + 卡钳",
    body: "同时选择轮毂和卡钳时，先保持新轮毂透视和轮辐结构，再把卡钳渲染在轮辐后方和刹车盘上，必须有正确遮挡和深度关系。",
    assetId: "",
    combinationKey: "wheels,calipers",
    active: true,
    sortOrder: 30,
  },
  {
    id: "tpl_combo_paint_carbon",
    scope: "combo",
    title: "组合 Prompt - 改色 + 碳纤维件",
    body: "同时选择车身改色和碳纤维配件时，车身漆面和外置碳纤维小件必须分开处理。只有 colorPolicy 为 body_color 的覆盖件才跟随车身同色；其余已选碳纤维小件保持碳纤维材质，但不能把车门、翼子板、玻璃、车顶或背景染黑。",
    assetId: "",
    combinationKey: "paint_change,carbon_parts",
    active: true,
    sortOrder: 40,
  },
  {
    id: "tpl_combo_aero_parts",
    scope: "combo",
    title: "组合 Prompt - 多个空气动力学套件",
    body: "当前唇、侧裙、尾翼、扩散器等多个空气动力学套件同时出现时，每个配件必须贴合自己的安装区域。不要把前唇、侧裙、扩散器和尾翼融合成一整块，也不要过度夸张。",
    assetId: "",
    combinationKey: "front-bumper,carbon_parts",
    active: true,
    sortOrder: 50,
  },
  {
    id: "tpl_combo_uploaded_reference",
    scope: "combo",
    title: "组合 Prompt - 多参考图",
    body: "所有参考图只服务于对应配件的形状、材质和安装关系。不要继承参考图里的车身、背景、文字、水印、车牌、轮毂、尾灯、排气、场景或拍摄角度。如果参考图角度难以对齐，宁可弱化配件，也不要改原车、背景或未选类别。",
    assetId: "",
    combinationKey: "uploaded_reference",
    active: true,
    sortOrder: 60,
  },
  {
    id: "tpl_combo_hood_body_color",
    scope: "combo",
    title: "组合 Prompt - 机盖车身同色",
    body: "当机盖 colorPolicy 为 body_color 时，这是 Seibon OE-style contour hood 的同色机盖改装，不是保持原厂普通平机盖。\n\n机盖必须喷成第一张原车相同的车身漆，或当前配置指定的车身同色漆；不能出现黑色碳纤维、裸碳纹理、黑色面板、开孔、散热孔或赛车通风口。\n\n但机盖造型必须明显可识别：请在同色漆面上做出清晰但真实的中央 power dome 隆起、左右两条从前沿延伸到风挡附近的长折线、前沿与灯眉附近的细微高低变化。\n\n这些特征必须通过同色高光、阴影、反射弯折和钣金曲面体现，视觉上能一眼看出不是原厂平机盖。不要只做轻微高光变化；如果机盖看起来和原图普通机盖几乎一样，则本次机盖改装失败。\n\n只允许修改机盖面板本身。其它车身、车顶、翼子板、前杠、格栅、大灯、轮毂、玻璃、车牌和背景全部保持原图。",
    assetId: "",
    combinationKey: "hood,hood_body_color",
    active: true,
    sortOrder: 70,
  },
  {
    id: "tpl_combo_hood_exposed_carbon",
    scope: "combo",
    title: "组合 Prompt - 机盖裸碳",
    body: "当机盖 colorPolicy 为 exposed_carbon 时，只在机盖面板显示清晰但真实的裸露碳纤维纹理和反光。不能把碳纤维纹理扩散到车顶、后备箱、车门、翼子板、保险杠、后视镜、轮毂、灯具或未选择部件。",
    assetId: "",
    combinationKey: "hood,hood_exposed_carbon",
    active: true,
    sortOrder: 80,
  },
  {
    id: "tpl_chat_parser_default",
    scope: "chat_parser",
    title: "对话解析 Prompt - 自然语言转标准 JSON",
    body:
      "请把用户的自然语言改装需求解析成稳定标准 JSON。必须提取：车辆信息、是否改色、目标颜色、车身高度/姿态、配件类别、配件来源、参考图对应关系、风格关键词、必须保留的约束。允许的配件类别只包括：轮毂、卡钳、尾翼、侧裙、前铲、排气、机盖、后视镜、叶子板、后备箱盖。每个 parts 项必须包含 category、source、referenceImages、instruction、colorPolicy、colorPolicyPrompt，以及需要时的 options。卡钳 options 可包含 caliperColor 和 rotorOption；尾翼/侧裙/前铲 options 可包含 surfaceColor；排气 options 可包含 layout；机盖/后视镜/叶子板/后备箱盖只表达裸碳开关。缺少关键字段时返回 needs_followup，并只问一个最关键的追问。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 7,
  },
  {
    id: "tpl_chat_optimizer_default",
    scope: "chat_optimizer",
    title: "对话优化 Prompt - 明确改装需求",
    body: "把用户含糊的改装需求整理成一个明确、可执行的汽车局部改装指令，同时保留用户原意。若目标类别缺失，只提出一个最关键的追问；不要直接扩写成生图 Prompt。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 10,
  },
  {
    id: "tpl_vehicle_recognition_default",
    scope: "vehicle_recognition",
    title: "车辆识别 Prompt - 输入检测",
    body: "你是汽车车型识别助手。请判断用户上传图片是否为真实车辆照片，并返回严格 JSON。如果是车辆，必须给出一个确定、具体、规范化的最佳车型猜测，不要使用“可能是 / 疑似 / maybe / probably / looks like”等不确定话术。model 字段必须尽量包含品牌、车系/车型、车身形式和代号/世代；格式示例：BMW M4 coupe (F82)、Porsche 911 GT3 (992)、Toyota GR Supra coupe (A90)。不要只返回品牌或单个车系代号，例如不要只写 BMW、M4、911；如果画面信息不足但仍是车辆，也要填写最具体的 best guess，并用 confidence 表示不确定性。只有在完全无法判断为车辆或车辆主体不可识别时，model 才写 unknown，并给出 rejectReason。返回字段：isVehicle、model、make、series、generation、bodyStyle、view、confidence、qualityFlags、rejectReason。只返回 JSON，不要 Markdown。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 5,
  },
  {
    id: "tpl_part_recognition_default",
    scope: "part_recognition",
    title: "配件识别 Prompt - 参考图检测",
    body: "请检查用户上传的配件参考图，判断它最可能属于哪类汽车改装件：轮毂、刹车卡钳、尾翼、前铲、侧裙、排气、机盖、后视镜、叶子板、后备箱盖。不要把扩散器、灯膜、贴膜/颜色、中网作为可选配件类目。输出结构化结果，包含 category、confidence、visualFeatures、usableAsReference、rejectReason。不确定时标记 unknown，禁止编造品牌或型号。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 6,
  },
  {
    id: "tpl_negative_default",
    scope: "negative",
    title: "默认 Negative Prompt",
    body: promptSeed.negativePrompt,
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 10,
  },
  {
    id: "tpl_result_check_default",
    scope: "result_check",
    title: "结果检查 Prompt - 质量验收",
    body: "请对比原车图、标准 JSON、最终生成图，判断生成结果是否合格。检查项：是否仍是同一辆车、背景是否被改变、拍摄角度是否被改变、光照和阴影是否一致、车身是否变形、轮毂是否圆且位置正确、所需配件是否全部出现、colorPolicy 是否被执行、未选择区域是否保持不变、是否有水印/文字/人物/明显 AI 伪影。输出 passed、score、missingElements、wrongElements、badCaseTags、summary、retryPrompt。不合格时 retryPrompt 只描述需要修复的失败点。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 10,
  },
  {
    id: "tpl_retry_default",
    scope: "retry",
    title: "修复重试 Prompt - 只修失败点",
    body: "这是一次修复重试，不是重新设计。请只修复结果检查中指出的失败点：缺失配件、颜色错误、轮毂变形、卡钳位置错误、背景变化、角度变化、车身扭曲、水印文字等。已经正确的内容必须保持不变。必须恢复原车身份、原背景、原拍摄角度、原光照和真实照片质感。不要新增未选择配件，不要改变用户没有要求修改的区域。",
    assetId: "",
    combinationKey: "",
    active: true,
    sortOrder: 10,
  },
]

type RawProviderSeed = Omit<ProviderConfig, "options" | "builtIn">

const rawProviderSeed: RawProviderSeed[] = [
  { id: "mock", label: "Mock Render", baseUrl: "local://mock-render", modelName: "mock-render-v1", capabilities: ["image_generation"], enabled: true, active: true, hasApiKey: false, maskedKey: "", consoleUrl: "", updatedAt: 0 },
  { id: "openai", label: "GPT Image 2", baseUrl: "https://router.shengsuanyun.com/api/v1/images/generations", modelName: "openai/gpt-image-2", capabilities: ["image_generation"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://shengsuanyun.com", updatedAt: 0 },
  { id: "nano", label: "Nano Banana 2", baseUrl: "https://router.shengsuanyun.com/api/v1/images/edits", modelName: "google/gemini-3.1-flash-image-preview", capabilities: ["image_generation"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://shengsuanyun.com", updatedAt: 0 },
  { id: "provider_302_nano_banana2_async_edit", label: "302-Nano Banana 2 Async Edit", baseUrl: "https://api.302ai.cn/ws/api/v3/google/nano-banana-2/edit", modelName: "gemini-3.1-flash-image-preview", capabilities: ["image_generation"], enabled: false, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://app.302.ai", updatedAt: 0 },
  { id: "provider_80fce082", label: "302-GPT Image 2", baseUrl: "https://api.302ai.cn/v1/images/edits", modelName: "gpt-image-2", capabilities: ["image_generation"], enabled: false, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://app.302.ai", updatedAt: 0 },
  { id: "provider_yunwu_nano2_edit", label: "Yunwu Nano Banana 2 Gemini Edit", baseUrl: "https://yunwu.ai/v1beta/models/gemini-3.1-flash-image-preview:generateContent", modelName: "gemini-3.1-flash-image-preview", capabilities: ["image_generation"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://yunwu.ai", updatedAt: 0 },
  { id: "provider_yunwu_image_edit", label: "Yunwu GPT Image 2 Edit", baseUrl: "https://yunwu.ai/v1/images/edits", modelName: "gpt-image-2", capabilities: ["image_generation"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://yunwu.ai", updatedAt: 0 },
  { id: "mock-vision", label: "Mock Vision", baseUrl: "local://mock-vision", modelName: "mock-vision-v1", capabilities: ["vision"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "", updatedAt: 0 },
  { id: "openai-vision", label: "OpenAI Vision", baseUrl: "https://api.openai.com/v1", modelName: "gpt-4.1-mini", capabilities: ["vision"], enabled: false, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://platform.openai.com", updatedAt: 0 },
  { id: "mock-llm", label: "Mock LLM", baseUrl: "local://mock-llm", modelName: "mock-intent-parser-v1", capabilities: ["llm"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "", updatedAt: 0 },
  { id: "openai-llm", label: "GPT-5.4-mini", baseUrl: "https://router.shengsuanyun.com/api/v1/chat/completions", modelName: "openai/gpt-5.4-mini", capabilities: ["vision", "llm"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://shengsuanyun.com", updatedAt: 0 },
  { id: "provider_d77cadd5", label: "QWEN-3.6", baseUrl: "https://router.shengsuanyun.com/api/v1/chat/completions", modelName: "ali/qwen3.6-plus", capabilities: ["vision", "llm"], enabled: true, active: false, hasApiKey: false, maskedKey: "", consoleUrl: "https://shengsuanyun.com", updatedAt: 0 },
]

export const providerSeed: ProviderConfig[] = rawProviderSeed.map((provider) => ({
  ...provider,
  builtIn: provider.id === "mock" || provider.id === "mock-vision" || provider.id === "mock-llm",
  options: buildDefaultProviderOptions(provider.baseUrl, provider.modelName),
}))

export const guardrailSeed: GuardrailConfig = {
  id: "default",
  sop: "只允许汽车改装效果图生成。用户必须提供车辆照片，且需求必须与汽车配件、车漆、姿态、轮毂、刹车、排气、尾翼、前铲、侧裙或干碳外观件相关。",
  allowedDescription: "允许：基于真实车辆照片，对已选外观配件、车漆、姿态、轮毂、刹车、排气、尾翼、前铲、侧裙、机盖、后视镜、叶子板或后备箱盖做局部改装效果。",
  blockedTerms: "portrait,person,people,animal,food,house,building,logo,nude,weapon,violence,politics,人像,人物,动物,食物,建筑,武器",
  recommendedPrompts:
    "选择鸭尾并设为碳纤维，保留后保险杠和尾灯不变。\n选择红色卡钳并加大刹车盘，只修改轮辐后方卡钳和刹车盘。\n选择双边双出排气，保留车尾、尾灯、车牌和背景不变。\n打开干碳纤维部件里的机盖和后视镜，只在对应部位显示裸碳纹理。",
  mockMode: true,
  mockFailUploads: false,
  provider: "mock",
  updatedAt: 0,
}

export const siteConfigSeed: SiteConfig = {
  id: "default",
  publicAssetBaseUrl: "",
  updatedAt: 0,
}

function workflowNode(
  id: string,
  type: WorkflowNodeConfig["type"],
  label: string,
  x: number,
  y: number,
  patch: Partial<WorkflowNodeConfig> = {},
): WorkflowNodeConfig {
  return {
    id,
    type,
    label,
    description: "",
    position: { x, y },
    required: true,
    enabled: true,
    providerCapability: "",
    providerId: "",
    fallbackProviderId: "",
    promptTemplateId: "",
    failureStrategy: "stop",
    maxRetries: 0,
    config: {},
    ...patch,
  }
}

function workflowEdges(ids: string[]): WorkflowEdgeConfig[] {
  return ids.slice(0, -1).map((id, index) => ({
    id: `edge_${id}_${ids[index + 1]}`,
    source: id,
    target: ids[index + 1],
  }))
}

const recognitionNodes = [
  workflowNode("start", "start", "开始", 60, 180),
  workflowNode("input_validation", "input_validation", "输入校验", 270, 180, { description: "校验车辆图片、上传内容和识别范围。" }),
  workflowNode("vehicle_detection", "vehicle_detection", "车辆识别", 500, 130, {
    description: "识别原车车型、车身姿态和拍摄视角。",
    providerCapability: "vision",
    providerId: "openai-llm",
    promptTemplateId: "tpl_vehicle_recognition_default",
  }),
  workflowNode("part_detection", "part_detection", "配件识别", 500, 260, {
    description: "识别上传配件参考图的类别、可用视角和关键视觉特征。",
    providerCapability: "vision",
    providerId: "openai-llm",
    promptTemplateId: "tpl_part_recognition_default",
    required: false,
  }),
  workflowNode("end", "end", "结束", 760, 180),
]

const configGenerationNodes = [
  workflowNode("start", "start", "开始", 60, 180),
  workflowNode("json_builder", "json_builder", "标准 JSON 组装", 280, 180, { description: "根据配置选择组装标准 JSON。" }),
  workflowNode("prompt_builder", "prompt_builder", "提示词组装", 500, 180, {
    description: "从基础、配置、分类、配件、组合和负面模板组装最终生图提示词。",
    promptTemplateId: "tpl_config_mode_default",
  }),
  workflowNode("image_generation", "image_generation", "生图 / 修图", 740, 180, {
    description: "调用图像模型生成配置好的车辆改装效果。",
    providerCapability: "image_generation",
    providerId: "provider_yunwu_nano2_edit",
    fallbackProviderId: "",
    failureStrategy: "stop",
    config: { callFailurePolicy: "stop" },
  }),
  workflowNode("result_check", "result_check", "结果检查", 980, 180, {
    description: "检查已选配件是否出现，未选择区域是否保持不变。",
    providerCapability: "vision",
    providerId: "openai-llm",
    promptTemplateId: "tpl_result_check_default",
  }),
  workflowNode("retry", "retry", "修复重试", 1220, 180, {
    description: "当结果缺少已选改装项时，生成一次修复提示词。",
    enabled: false,
    promptTemplateId: "tpl_retry_default",
    failureStrategy: "retry",
    maxRetries: 0,
    config: { qualityFailurePolicy: "stop" },
  }),
  workflowNode("save_record", "save_record", "保存记录", 1460, 180),
  workflowNode("end", "end", "结束", 1680, 180),
]

const chatGenerationNodes = [
  workflowNode("start", "start", "开始", 60, 180),
  workflowNode("input_validation", "input_validation", "上传校验", 280, 180, {
    description: "本地校验文件数量、文件类型、上传大小和车辆画布。该节点不调用外部接口。",
  }),
  workflowNode("guardrail", "guardrail", "本地安全检查", 500, 180, {
    description: "本地检查请求安全、业务范围和硬性限制。该节点不调用外部接口。",
  }),
  workflowNode("vehicle_detection", "vehicle_detection", "车辆识别", 720, 110, {
    description: "调用视觉模型识别原车和相机视角。若画布已有识别结果可复用；对话模式不把识别车型当成最终身份。",
    providerCapability: "vision",
    providerId: "openai-llm",
    promptTemplateId: "tpl_vehicle_recognition_default",
  }),
  workflowNode("part_detection", "part_detection", "配件识别", 720, 250, {
    description: "调用视觉模型识别上传配件参考图的类别和视觉特征；识别结果仍会回到本地规则校验。",
    providerCapability: "vision",
    providerId: "openai-llm",
    promptTemplateId: "tpl_part_recognition_default",
    required: false,
  }),
  workflowNode("local_parser", "local_parser", "本地规则解析", 960, 180, {
    description: "本地规则解析颜色、车身高度、配件、参考图、上下文选择和碳纤维颜色策略。该节点不调用外部接口。",
  }),
  workflowNode("intent_parser", "intent_parser", "大模型兜底解析", 1200, 180, {
    description: "仅在本地解析低置信且字段可补全时调用。模型只输出窄意图结果，不直接生成最终标准参数。",
    providerCapability: "llm",
    providerId: "openai-llm",
    promptTemplateId: "tpl_chat_parser_default",
    failureStrategy: "follow_up",
  }),
  workflowNode("follow_up_gate", "follow_up_gate", "追问 / 确认", 1440, 180, {
    description: "本地处理追问、上下文确认、配件参考图要求和碳纤维颜色策略确认。该节点不调用外部接口。",
  }),
  workflowNode("json_builder", "json_builder", "标准 JSON 组装", 1680, 180, {
    description: "在确定性解析、大语言模型兜底回流和确认门完成后，本地组装标准生成参数。该节点不调用外部接口。",
  }),
  workflowNode("prompt_builder", "prompt_builder", "提示词组装", 1920, 180, {
    description: "本地组装对话模式的最终生图提示词，并应用保护项、参考图分配和模型预算。",
    promptTemplateId: "tpl_chat_mode_default",
  }),
  workflowNode("image_generation", "image_generation", "生图 / 修图", 2160, 180, {
    description: "调用图像生成模型执行车辆改装效果生成。备用模型会按自身参考图预算重新选择上传图片。",
    providerCapability: "image_generation",
    providerId: "provider_yunwu_nano2_edit",
    fallbackProviderId: "",
    failureStrategy: "stop",
    config: { callFailurePolicy: "stop" },
  }),
  workflowNode("result_check", "result_check", "结果检查", 2400, 180, {
    description: "本地模拟只做轻量检查：是否有结果图、是否有可见修改需求。切换真实视觉模型后，才会对比原图和结果图检查颜色、配件、车高和保护项。",
    providerCapability: "vision",
    providerId: "openai-llm",
    promptTemplateId: "tpl_result_check_default",
    config: { qualityFailurePolicy: "save_bad_case" },
  }),
  workflowNode("retry", "retry", "修复重试", 2640, 180, {
    description: "当真实视觉结果检查发现关键需求缺失时，可生成一次修复 prompt。默认不自动重试。",
    promptTemplateId: "tpl_retry_default",
    failureStrategy: "retry",
    maxRetries: 0,
    config: { qualityFailurePolicy: "save_bad_case" },
  }),
  workflowNode("save_record", "save_record", "保存记录", 2880, 180),
  workflowNode("end", "end", "结束", 3120, 180),
]

export const workflowSeed: WorkflowConfig[] = [
  {
    id: "workflow_input_detection",
    mode: "recognition",
    title: "图片识别 / 输入检测 Workflow",
    enabled: true,
    vehicleCheckEnabled: true,
    partCheckEnabled: true,
    allowFollowUp: false,
    promptTemplateIds: ["tpl_vehicle_recognition_default", "tpl_part_recognition_default"],
    providerId: "openai-llm",
    fallbackProviderId: "",
    resultCheckEnabled: false,
    autoRetryEnabled: false,
    maxRetries: 0,
    nodes: recognitionNodes,
    edges: workflowEdges(["start", "input_validation", "vehicle_detection", "part_detection", "end"]),
    updatedAt: 0,
  },
  {
    id: "workflow_config_default",
    mode: "config",
    title: "配置模式生图 Workflow",
    enabled: true,
    vehicleCheckEnabled: true,
    partCheckEnabled: false,
    allowFollowUp: false,
    promptTemplateIds: ["tpl_base_photo_edit", "tpl_config_mode_default", "tpl_config_base_default", "tpl_negative_default", "tpl_result_check_default", "tpl_retry_default"],
    providerId: "provider_yunwu_nano2_edit",
    fallbackProviderId: "",
    resultCheckEnabled: true,
    autoRetryEnabled: false,
    maxRetries: 0,
    nodes: configGenerationNodes,
    edges: workflowEdges(["start", "json_builder", "prompt_builder", "image_generation", "result_check", "retry", "save_record", "end"]),
    updatedAt: 0,
  },
  {
    id: "workflow_chat_default",
    mode: "chat",
    title: "对话模式生图 Workflow",
    enabled: true,
    vehicleCheckEnabled: true,
    partCheckEnabled: true,
    allowFollowUp: true,
    promptTemplateIds: ["tpl_vehicle_recognition_default", "tpl_part_recognition_default", "tpl_base_photo_edit", "tpl_chat_mode_default", "tpl_negative_default", "tpl_result_check_default", "tpl_retry_default"],
    providerId: "provider_yunwu_nano2_edit",
    fallbackProviderId: "",
    resultCheckEnabled: true,
    autoRetryEnabled: false,
    maxRetries: 0,
    nodes: chatGenerationNodes,
    edges: workflowEdges(["start", "input_validation", "guardrail", "vehicle_detection", "part_detection", "local_parser", "intent_parser", "follow_up_gate", "json_builder", "prompt_builder", "image_generation", "result_check", "retry", "save_record", "end"]),
    updatedAt: 0,
  },
]
